import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Light" }
bold = { style = "medium" }
size = 16

[cursor]
style = { blinking = "Always" }
blink_interval = 100
blink_timeout = 0
unfocused_hollow = true
# thickness = 1

[window]
# padding = { x = 0, y = 5 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.95
blur = true

[env]
TERM = "xterm-256color"
