# theme
include dracula.conf

# text
font_family                 JetBrainsMono Nerd Font Mono
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
font_size                   14
disable_ligatures           never
# inactive_text_alpha         0.3

# notifications
confirm_os_window_close     0
enable_audio_bell           no
paste_actions               no-op

# window
titlebar-only               no
hide_window_decorations     titlebar-only
window_padding_width        20 0 20 0
remember_window_position    no
remember_window_size        no

# background
# background_image            ~/Pictures/autechre.jpg
# background_image            ~/Pictures/boards.jpg
background_image            ~/Pictures/abigor2.jpg
background_image_layout     cscaled
background_tint             0.85


# logo
# window_logo_path            ~/.config/kitty/logo.png
window_logo_scale           0
window_logo_position        top-right
window_logo_alpha           .1



# cursor
cursor_shape                beam
cursor_blink_interval       0.1
cursor                      #ffa548
cursor_text_color           #252535
cursor_trail                4
cursor_trail_decay          0.1 0.4
cursor_trail_color          #FFB86C

# scrollback
scrollback_pager nvim +"source /Users/david.diosdado/.config/kitty/vi-mode.lua"
map alt+return show_scrollback

# disable new windows and tabs
map cmd+k no_op
map cmd+n no_op
map cmd+t no_op
map cmd+l no_op

# remap control tab for tmux windows
map ctrl+tab send_text all \x1b[27;5;9~
map ctrl+shift+tab send_text all \x1b[27;6;9~

