include dracula.conf

font_family                 JetBrainsMono Nerd Font Mono
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
font_size                   14
disable_ligatures           never
inactive_text_alpha         0.3

notify_on_cmd_finish        always
confirm_os_window_close     0
enable_audio_bell           no
paste_actions               no-op

# window_logo_path            ~/.config/kitty/kitty.png
# window_logo_scale           50
# window_logo_position        top-right
# window_logo_alpha           0.3

remember_window_position    no
remember_window_size        no

titlebar-only               no
hide_window_decorations     titlebar-only
background_opacity          0.98
background_blur             20
draw_minimal_borders        no
window_padding_width        20 0 20 0

cursor_shape                beam
cursor_blink_interval       0.1
cursor                      #ffa548
cursor_text_color           #252535
cursor_trail                4
cursor_trail_decay          0.1 0.4
cursor_trail_color          #FFB86C

scrollback_pager nvim +"source /Users/david.diosdado/.config/kitty/vi-mode.lua"

map alt+return show_scrollback
map cmd+k no_op
map cmd+n no_op

# mac navigation
# map alt+left send_text all \x1b\x62
# map alt+right send_text all \x1b\x66
